name: logger_flutter_plus
description: Flutter extension for logger. Please go there for documentation.
version: 1.1.0

homepage: https://github.com/Oliinyk-Volodymyr/logger_flutter_plus

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.0.2+1
  collection: ^1.18.0
  sensors_plus: ^4.0.2
